# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
dist: trusty
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-chrome-addon-in-the-headless-mode
addons:
  chrome: stable
node_js:
  - 10
  - 8
sudo: false
before_script:
  - sh test/server-start.sh &
  - SERVER_PID=$!
  - sleep 1
  - which google-chrome-stable && google-chrome-stable --version
after_script:
  - kill $SERVER_PID
script: "npm test && npm run-script lint"
cache:
  directories:
    - node_modules
