name: Check if a Docker image can be built

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --tag ${{ github.repository }}
        docker images

    - name: Run tests inside the Docker container
      run: |
        ./test/server-start.sh &
        sleep 5
        docker ps
        curl -svo /dev/null 0.0.0.0:8888

        docker run --network=host ${{ github.repository }} npm t
