name: Check if a Docker image can be built

on: [push, pull_request]

jobs:

  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --tag ${{ github.repository }}
        docker images

    - name: Run tests inside the Docker container
      run: |
        ./test/server-start.sh

        docker run \
          --network=host \
          --security-opt seccomp=$(pwd)/chrome-seccomp.json \
          ${{ github.repository }} npm t
