name: Check if a Docker image can be built

on:
  push:
    branches: [ devel ]
  pull_request:

jobs:

  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      env:
        # @see https://testdriven.io/blog/faster-ci-builds-with-docker-cache/
        CACHE_IMAGE: macbre/phantomas:latest
        # @see https://docs.docker.com/develop/develop-images/build_enhancements/
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
      run: |
        docker pull $CACHE_IMAGE
        docker build . \
          --cache-from $CACHE_IMAGE \
          --tag ${{ github.repository }}
        docker images

    - name: Run tests inside the Docker container
      run: |
        ./test/server-start.sh

        docker run \
          --network=host \
          --security-opt seccomp=$(pwd)/chrome-seccomp.json \
          ${{ github.repository }} npm t
