name: Check if a Docker image can be built

on:
  push:
    branches: [ devel ]
  pull_request:

jobs:

  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ github.repository }}
        build-args: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
        cache-from: |
          macbre/phantomas:latest

    - name: Inspect built image
      run: |
        docker images
        docker inspect --format='{{json .Config.Labels}}' ${{ github.repository }} | jq

    - name: Run tests inside the Docker container
      run: |
        ./test/server-start.sh

        docker run \
          --network=host \
          --security-opt seccomp=$(pwd)/chrome-seccomp.json \
          ${{ github.repository }} npm t
