# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        docker run --detach --rm -p 0.0.0.0:8888:8888 -v "$PWD":/app -w /app node:12-alpine ./test/server-start.sh
        sleep 5
        docker ps
        curl -svo /dev/null 0.0.0.0:8888

        npm test
        npm run-script lint

    - name: Check that bin/phantomas.js works
      run: ./bin/phantomas.js http://127.0.0.1:8888/ --pretty | grep "generator" -A4
